/*
 * CRUK-CI Clarity REST API Java Client.
 * Copyright (C) 2013 Cancer Research UK Cambridge Institute.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2013.02.01 at 10:52:03 AM GMT
//

package com.genologics.ri.containertype;

import java.io.Serializable;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;

/**
 *
 * Dimension is a child element of container type and describes the size and
 * identification method of the horizontal and vertical dimensions of the
 * coordinate system of the container type.
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "dimension", propOrder = { "alpha", "offset", "size" })
public class Dimension implements Serializable
{
    private static final long serialVersionUID = -1931190014491768673L;

    /**
     * Whether numbering in this dimension is using letters (true) or numbers (false).
     */
    @XmlElement(name = "is-alpha")
    protected Boolean alpha;

    protected Integer offset;

    protected Integer size;

    public Dimension()
    {
    }

    public Dimension(Integer size)
    {
        this.size = size;
    }

    public Boolean isAlpha()
    {
        return alpha;
    }

    public void setAlpha(Boolean alpha)
    {
        this.alpha = alpha;
    }

    public Integer getOffset()
    {
        return offset;
    }

    public void setOffset(Integer offset)
    {
        this.offset = offset;
    }

    public Integer getSize()
    {
        return size;
    }

    public void setSize(Integer size)
    {
        this.size = size;
    }

}
